name: CI

on:
  push:
    branches:
      - main
    tags: ['*']
    paths-ignore:
      - 'docs/**'
      - '.github/workflows/Documenter.yml'
      - '.github/workflows/DocPreviewCleanup.yml'
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - '.github/workflows/Documenter.yml'
      - '.github/workflows/DocPreviewCleanup.yml'
  workflow_dispatch:

concurrency:
  # Skip intermediate builds: always.
  # Cancel intermediate builds: only if it is a pull request build.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  test-core:
    name: Julia 1.10 - core tests - ubuntu-latest - x64 - ${{ github.event_name }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: julia-actions/setup-julia@v2
        with:
          version: '1.10'
          arch: x64
          show-versioninfo: true
      - uses: julia-actions/cache@v2

      - name: Run core tests
        run: julia --project=. -e 'using Pkg; Pkg.test(test_args=["core"])'

  test-visualization:
    name: Julia 1.10 - visualization tests - ubuntu-latest - x64 - ${{ github.event_name }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: julia-actions/setup-julia@v2
        with:
          version: '1.10'
          arch: x64
          show-versioninfo: true
      - uses: julia-actions/cache@v2

      - name: Run visualization tests
        run: julia --project=. -e 'using Pkg; Pkg.test(test_args=["visualization"])'
